name: auth_repository
description: Auth Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  api_client:
    path: ../api_client
  app_http_client:
    path: ../app_http_client

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
