name: andina_flutter_challenge
description: "Andina Flutter Challenge"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  api_client:
    path: packages/api_client
  auth_repository:
    path: packages/auth_repository
  beneficiaries_repository:
    path: packages/beneficiaries_repository
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  user_repository:
    path: packages/user_repository
  uuid_service:
    path: packages/uuid_service
  transactions_repository:
    path: packages/transactions_repository
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7


flutter:
  uses-material-design: true

