name: app_http_client
description: App Http Client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2

dependencies:
  flutter_secure_storage: ^4.2.1

